# TCL File Generated by Component Editor 20.1
# Wed Jun 08 15:30:19 IDT 2022
# DO NOT MODIFY


# 
# FFtMagnitude "FFtMagnitude" v1.0
#  2022.06.08.15:30:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module FFtMagnitude
# 
set_module_property DESCRIPTION ""
set_module_property NAME FFtMagnitude
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP VincNL
set_module_property AUTHOR "Nitzan Lavi"
set_module_property DISPLAY_NAME FFtMagnitude
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fft_magnitude
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fft_magnitude.vhd VHDL PATH ../fft_magnitude.vhd TOP_LEVEL_FILE

set_module_property ELABORATION_CALLBACK    elaborate_me

# 
# parameters
# 

add_parameter FFT_WIDTH POSITIVE 16
set_parameter_property FFT_WIDTH DEFAULT_VALUE 16
set_parameter_property FFT_WIDTH DISPLAY_NAME "FFT Data Width"
set_parameter_property FFT_WIDTH TYPE INTEGER
set_parameter_property FFT_WIDTH UNITS Bits
set_parameter_property FFT_WIDTH ALLOWED_RANGES {8 10 12 14 16 18 20 24 28 32}
set_parameter_property FFT_WIDTH DESCRIPTION "Width of FFT vector"
set_parameter_property FFT_WIDTH AFFECTS_GENERATION true 
set_parameter_property FFT_WIDTH HDL_PARAMETER true

add_parameter PACKET_LEN POSITIVE 1024
set_parameter_property PACKET_LEN DEFAULT_VALUE 8192
set_parameter_property PACKET_LEN DISPLAY_NAME "Length"
set_parameter_property PACKET_LEN TYPE INTEGER
set_parameter_property PACKET_LEN UNITS None
set_parameter_property PACKET_LEN ALLOWED_RANGES \
{8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144}
set_parameter_property PACKET_LEN DESCRIPTION "Transform length"
set_parameter_property PACKET_LEN AFFECTS_GENERATION true 
set_parameter_property PACKET_LEN HDL_PARAMETER true

add_parameter AV_DATA_WIDTH INTEGER 47 ""
set_parameter_property AV_DATA_WIDTH DEFAULT_VALUE 47
set_parameter_property AV_DATA_WIDTH TYPE INTEGER
set_parameter_property AV_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AV_DATA_WIDTH DERIVED true
set_parameter_property AV_DATA_WIDTH HDL_PARAMETER true
set_parameter_property AV_DATA_WIDTH AFFECTS_ELABORATION true
set_parameter_property AV_DATA_WIDTH VISIBLE false


#-------------------------------------------------------------------------------
# module GUI
#-------------------------------------------------------------------------------         

# display group
add_display_item {} {Transform} GROUP  

# group parameter
add_display_item {Transform} PACKET_LEN PARAMETER
add_display_item {Transform} FFT_WIDTH PARAMETER


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point fftout
# 
add_interface fftout avalon_streaming end
set_interface_property fftout associatedClock clock
set_interface_property fftout associatedReset reset
set_interface_property fftout dataBitsPerSymbol 8
set_interface_property fftout errorDescriptor ""
set_interface_property fftout firstSymbolInHighOrderBits true
set_interface_property fftout maxChannel 0
set_interface_property fftout readyLatency 0
set_interface_property fftout ENABLED true
set_interface_property fftout EXPORT_OF ""
set_interface_property fftout PORT_NAME_MAP ""
set_interface_property fftout CMSIS_SVD_VARIABLES ""
set_interface_property fftout SVD_ADDRESS_GROUP ""

add_interface_port fftout asi_fftout_data data Input 8
add_interface_port fftout asi_fftout_valid valid Input 1
add_interface_port fftout asi_fftout_ready ready Output 1
add_interface_port fftout asi_fftout_eop endofpacket Input 1
add_interface_port fftout asi_fftout_sop startofpacket Input 1


# 
# connection point fftmagnitude
# 
add_interface fftmagnitude avalon_streaming start
set_interface_property fftmagnitude associatedClock clock
set_interface_property fftmagnitude associatedReset reset
set_interface_property fftmagnitude dataBitsPerSymbol 16
set_interface_property fftmagnitude errorDescriptor ""
set_interface_property fftmagnitude firstSymbolInHighOrderBits true
set_interface_property fftmagnitude maxChannel 0
set_interface_property fftmagnitude readyLatency 0
set_interface_property fftmagnitude ENABLED true
set_interface_property fftmagnitude EXPORT_OF ""
set_interface_property fftmagnitude PORT_NAME_MAP ""
set_interface_property fftmagnitude CMSIS_SVD_VARIABLES ""
set_interface_property fftmagnitude SVD_ADDRESS_GROUP ""

add_interface_port fftmagnitude aso_fftmagnitude_data data Output FFT_WIDTH
add_interface_port fftmagnitude aso_fftmagnitude_valid valid Output 1
add_interface_port fftmagnitude aso_fftmagnitude_ready ready Input 1
add_interface_port fftmagnitude aso_fftmagnitude_eop endofpacket Output 1
add_interface_port fftmagnitude aso_fftmagnitude_sop startofpacket Output 1

proc elaborate_me {}  {
    set data_width [get_parameter_value FFT_WIDTH]
    set packet_len [get_parameter_value PACKET_LEN]
    
    set data_width [expr {$data_width + $data_width}] 
    set data_width [ expr 1 + $data_width + [ log2ceil $packet_len ] ]
    set_interface_property fftout dataBitsPerSymbol $data_width
    add_interface_port fftout asi_fftout_data data Input $data_width
    set_parameter_value AV_DATA_WIDTH $data_width

}

proc log2ceil {num} {
    set val 0
    set i 1
    while { $i < $num } {
        set val [ expr $val + 1 ]
        set i [ expr 1 << $val ]
    }
    return $val;
}