# TCL File Generated by Component Editor 20.1
# Wed Jun 08 15:30:58 IDT 2022
# DO NOT MODIFY


# 
# NcoController "NcoController" v1.0
#  2022.06.08.15:30:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module NcoController
# 
set_module_property DESCRIPTION ""
set_module_property NAME NcoController
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP VincNL
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME NcoController
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nco_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nco_controller.vhd VHDL PATH ../nco_controller.vhd TOP_LEVEL_FILE

set_module_property ELABORATION_CALLBACK elaborate_me
# 
# parameters
# 
add_parameter NCO_PHASE_WIDTH INTEGER 32
set_parameter_property NCO_PHASE_WIDTH DEFAULT_VALUE 32
set_parameter_property NCO_PHASE_WIDTH DISPLAY_NAME NCO_PHASE_WIDTH
set_parameter_property NCO_PHASE_WIDTH TYPE INTEGER
set_parameter_property NCO_PHASE_WIDTH UNITS None
set_parameter_property NCO_PHASE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NCO_PHASE_WIDTH HDL_PARAMETER true

add_parameter NCO_WIDTH INTEGER 16
set_parameter_property NCO_WIDTH DEFAULT_VALUE 16
set_parameter_property NCO_WIDTH DISPLAY_NAME NCO_WIDTH
set_parameter_property NCO_WIDTH TYPE INTEGER
set_parameter_property NCO_WIDTH UNITS None
set_parameter_property NCO_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NCO_WIDTH HDL_PARAMETER true

add_parameter FFT_WIDTH INTEGER 16
set_parameter_property FFT_WIDTH DEFAULT_VALUE 16
set_parameter_property FFT_WIDTH DISPLAY_NAME FFT_WIDTH
set_parameter_property FFT_WIDTH TYPE INTEGER
set_parameter_property FFT_WIDTH UNITS None
set_parameter_property FFT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FFT_WIDTH HDL_PARAMETER true

add_parameter PACKET_LEN INTEGER 8192
set_parameter_property PACKET_LEN DEFAULT_VALUE 8192
set_parameter_property PACKET_LEN DISPLAY_NAME PACKET_LEN
set_parameter_property PACKET_LEN TYPE INTEGER
set_parameter_property PACKET_LEN UNITS None
set_parameter_property PACKET_LEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PACKET_LEN HDL_PARAMETER true

add_parameter FIFO_DEPTH INTEGER 8192
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 8192
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true

add_parameter AV_DATA_WIDTH INTEGER 47 ""
set_parameter_property AV_DATA_WIDTH DEFAULT_VALUE 47
set_parameter_property AV_DATA_WIDTH TYPE INTEGER
set_parameter_property AV_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AV_DATA_WIDTH DERIVED true
set_parameter_property AV_DATA_WIDTH HDL_PARAMETER true
set_parameter_property AV_DATA_WIDTH AFFECTS_ELABORATION true
set_parameter_property AV_DATA_WIDTH VISIBLE false

add_parameter CLK_FREQ INTEGER 50000000
set_parameter_property CLK_FREQ DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQ DISPLAY_NAME CLK_FREQ
set_parameter_property CLK_FREQ TYPE INTEGER
set_parameter_property CLK_FREQ UNITS None
set_parameter_property CLK_FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point ncoin
# 
add_interface ncoin avalon_streaming start
set_interface_property ncoin associatedClock clock
set_interface_property ncoin associatedReset reset
set_interface_property ncoin dataBitsPerSymbol 32
set_interface_property ncoin errorDescriptor ""
set_interface_property ncoin firstSymbolInHighOrderBits true
set_interface_property ncoin maxChannel 0
set_interface_property ncoin readyLatency 0
set_interface_property ncoin ENABLED true
set_interface_property ncoin EXPORT_OF ""
set_interface_property ncoin PORT_NAME_MAP ""
set_interface_property ncoin CMSIS_SVD_VARIABLES ""
set_interface_property ncoin SVD_ADDRESS_GROUP ""

add_interface_port ncoin aso_ncoin_data data Output nco_phase_width
add_interface_port ncoin aso_ncoin_valid valid Output 1


# 
# connection point ncoout
# 
add_interface ncoout avalon_streaming end
set_interface_property ncoout associatedClock clock
set_interface_property ncoout associatedReset reset
set_interface_property ncoout dataBitsPerSymbol 16
set_interface_property ncoout errorDescriptor ""
set_interface_property ncoout firstSymbolInHighOrderBits true
set_interface_property ncoout maxChannel 0
set_interface_property ncoout readyLatency 0
set_interface_property ncoout ENABLED true
set_interface_property ncoout EXPORT_OF ""
set_interface_property ncoout PORT_NAME_MAP ""
set_interface_property ncoout CMSIS_SVD_VARIABLES ""
set_interface_property ncoout SVD_ADDRESS_GROUP ""

add_interface_port ncoout asi_ncoout_data data Input nco_width
add_interface_port ncoout asi_ncoout_valid valid Input 1


# 
# connection point fftin
# 
add_interface fftin avalon_streaming start
set_interface_property fftin associatedClock clock
set_interface_property fftin associatedReset reset
set_interface_property fftin dataBitsPerSymbol 8
set_interface_property fftin errorDescriptor ""
set_interface_property fftin firstSymbolInHighOrderBits true
set_interface_property fftin maxChannel 0
set_interface_property fftin readyLatency 0
set_interface_property fftin ENABLED true
set_interface_property fftin EXPORT_OF ""
set_interface_property fftin PORT_NAME_MAP ""
set_interface_property fftin CMSIS_SVD_VARIABLES ""
set_interface_property fftin SVD_ADDRESS_GROUP ""

add_interface_port fftin aso_fftin_data data Output 8
add_interface_port fftin aso_fftin_valid valid Output 1
add_interface_port fftin aso_fftin_ready ready Input 1
add_interface_port fftin aso_fftin_eop endofpacket Output 1
add_interface_port fftin aso_fftin_sop startofpacket Output 1

# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_address address Input 4
add_interface_port csr avs_csr_writedata writedata Input 32
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_readdata readdata Output 32
add_interface_port csr avs_csr_read read Input 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

proc elaborate_me {}  {
    set data_width [get_parameter_value FFT_WIDTH]
    set packet_len [get_parameter_value PACKET_LEN]
    
    set data_width [expr {$data_width + $data_width}] 
    set data_width [ expr 2 + $data_width + [ log2ceil $packet_len ] ]
    set_interface_property fftin dataBitsPerSymbol $data_width
    add_interface_port fftin aso_fftin_data data Output $data_width
    set_parameter_value AV_DATA_WIDTH $data_width
}

proc log2ceil {num} {
    set val 0
    set i 1
    while { $i < $num } {
        set val [ expr $val + 1 ]
        set i [ expr 1 << $val ]
    }
    return $val;
}