# TCL File Generated by Component Editor 20.1
# Wed Jun 01 12:29:36 IDT 2022
# DO NOT MODIFY


# 
# PacketDecimation "PacketDecimation" v1.0
#  2022.06.01.12:29:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module PacketDecimation
# 
set_module_property DESCRIPTION ""
set_module_property NAME PacketDecimation
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP VincNL
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME PacketDecimation
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL packet_decimation
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file packet_decimation.vhd VHDL PATH ../packet_decimation.vhd TOP_LEVEL_FILE

set_module_property ELABORATION_CALLBACK    elaborate_me
set_module_property VALIDATION_CALLBACK     validate_me
# 
# parameters
# 
add_parameter CLK_FREQ INTEGER 50000000
set_parameter_property CLK_FREQ DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQ DISPLAY_NAME {Clock Frequency}
set_parameter_property CLK_FREQ TYPE INTEGER
set_parameter_property CLK_FREQ UNITS {Hertz}
set_parameter_property CLK_FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ DESCRIPTION {In Clock Frequency}
set_parameter_property CLK_FREQ HDL_PARAMETER true

add_parameter PACKET_RATE INTEGER 60
set_parameter_property PACKET_RATE DEFAULT_VALUE 60
set_parameter_property PACKET_RATE DISPLAY_NAME {Packet Rate}
set_parameter_property PACKET_RATE TYPE INTEGER
set_parameter_property PACKET_RATE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PACKET_RATE DESCRIPTION {Packets Per Second}
set_parameter_property PACKET_RATE HDL_PARAMETER true

add_parameter PACKET_LEN POSITIVE 1024
set_parameter_property PACKET_LEN DEFAULT_VALUE 8192
set_parameter_property PACKET_LEN DISPLAY_NAME {Length}
set_parameter_property PACKET_LEN TYPE INTEGER
set_parameter_property PACKET_LEN UNITS None
set_parameter_property PACKET_LEN ALLOWED_RANGES \
{8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144}
set_parameter_property PACKET_LEN DESCRIPTION {Packet length}
set_parameter_property PACKET_LEN AFFECTS_GENERATION true 
set_parameter_property PACKET_LEN HDL_PARAMETER true

add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME {Data Width}
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS bits
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32 64 128 256 512 1024}
set_parameter_property DATA_WIDTH DESCRIPTION {Data width}
set_parameter_property DATA_WIDTH AFFECTS_GENERATION {1}
set_parameter_property DATA_WIDTH HDL_PARAMETER true
 
add_parameter USE_FIX_ADDRESS_WIDTH Integer 0 "Use pre-determined master address width instead of automatically-determined master address width"
set_parameter_property USE_FIX_ADDRESS_WIDTH DISPLAY_NAME "Use pre-determined master address width"
set_parameter_property USE_FIX_ADDRESS_WIDTH DISPLAY_HINT boolean
set_parameter_property USE_FIX_ADDRESS_WIDTH AFFECTS_GENERATION false
set_parameter_property USE_FIX_ADDRESS_WIDTH DERIVED false
set_parameter_property USE_FIX_ADDRESS_WIDTH HDL_PARAMETER false
set_parameter_property USE_FIX_ADDRESS_WIDTH AFFECTS_ELABORATION true
add_display_item "Transfer Options" USE_FIX_ADDRESS_WIDTH parameter

add_parameter FIX_ADDRESS_WIDTH INTEGER 32 "Minimum master address width that is required to address memory slave."
set_parameter_property FIX_ADDRESS_WIDTH DISPLAY_NAME "Pre-determined master address width:"
set_parameter_property FIX_ADDRESS_WIDTH ALLOWED_RANGES 1:64
set_parameter_property FIX_ADDRESS_WIDTH AFFECTS_GENERATION true
set_parameter_property FIX_ADDRESS_WIDTH DERIVED false
set_parameter_property FIX_ADDRESS_WIDTH HDL_PARAMETER false
set_parameter_property FIX_ADDRESS_WIDTH AFFECTS_ELABORATION true
set_parameter_property FIX_ADDRESS_WIDTH VISIBLE true
add_display_item "Transfer Options" FIX_ADDRESS_WIDTH parameter

add_parameter AUTO_ADDRESS_WIDTH INTEGER 32
set_parameter_property AUTO_ADDRESS_WIDTH AFFECTS_GENERATION false
set_parameter_property AUTO_ADDRESS_WIDTH DERIVED true
set_parameter_property AUTO_ADDRESS_WIDTH HDL_PARAMETER false
set_parameter_property AUTO_ADDRESS_WIDTH AFFECTS_ELABORATION true
set_parameter_property AUTO_ADDRESS_WIDTH VISIBLE false
set_parameter_property AUTO_ADDRESS_WIDTH SYSTEM_INFO {ADDRESS_WIDTH mem}

add_parameter ADDRESS_WIDTH INTEGER 32
set_parameter_property ADDRESS_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDRESS_WIDTH DERIVED true
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
set_parameter_property ADDRESS_WIDTH AFFECTS_ELABORATION true
set_parameter_property ADDRESS_WIDTH VISIBLE false


#-------------------------------------------------------------------------------
# module GUI
#-------------------------------------------------------------------------------         

# display group
add_display_item {} {Clock} GROUP
add_display_item {} {Packet} GROUP
add_display_item {} {Memory Write Master} GROUP

# group parameter
add_display_item {Clock} CLK_FREQ PARAMETER

add_display_item {Packet} PACKET_LEN PARAMETER
add_display_item {Packet} PACKET_RATE PARAMETER

add_display_item {Memory Write Master} DATA_WIDTH PARAMETER
add_display_item {Memory Write Master} USE_FIX_ADDRESS_WIDTH PARAMETER
add_display_item {Memory Write Master} FIX_ADDRESS_WIDTH PARAMETER


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point fftin
# 
add_interface fftin avalon_streaming end
set_interface_property fftin associatedClock clock
set_interface_property fftin associatedReset reset
set_interface_property fftin errorDescriptor ""
set_interface_property fftin firstSymbolInHighOrderBits true
set_interface_property fftin maxChannel 0
set_interface_property fftin readyLatency 0
set_interface_property fftin ENABLED true
set_interface_property fftin EXPORT_OF ""
set_interface_property fftin PORT_NAME_MAP ""
set_interface_property fftin CMSIS_SVD_VARIABLES ""
set_interface_property fftin SVD_ADDRESS_GROUP ""

add_interface_port fftin asi_fftin_data data Input data_width
add_interface_port fftin asi_fftin_valid valid Input 1
add_interface_port fftin asi_fftin_ready ready Output 1
add_interface_port fftin asi_fftin_eop endofpacket Input 1
add_interface_port fftin asi_fftin_sop startofpacket Input 1


# 
# connection point mem
# 
add_interface mem avalon start
set_interface_property mem addressUnits SYMBOLS
set_interface_property mem associatedClock clock
set_interface_property mem associatedReset reset
set_interface_property mem bitsPerSymbol 8
set_interface_property mem burstOnBurstBoundariesOnly false
set_interface_property mem burstcountUnits WORDS
set_interface_property mem doStreamReads false
set_interface_property mem doStreamWrites false
set_interface_property mem holdTime 0
set_interface_property mem linewrapBursts false
set_interface_property mem maximumPendingReadTransactions 0
set_interface_property mem maximumPendingWriteTransactions 0
set_interface_property mem readLatency 0
set_interface_property mem readWaitTime 1
set_interface_property mem setupTime 0
set_interface_property mem timingUnits Cycles
set_interface_property mem writeWaitTime 0
set_interface_property mem ENABLED true
set_interface_property mem EXPORT_OF ""
set_interface_property mem PORT_NAME_MAP ""
set_interface_property mem CMSIS_SVD_VARIABLES ""
set_interface_property mem SVD_ADDRESS_GROUP ""

add_interface_port mem avm_mem_address address Output -1
add_interface_port mem avm_mem_waitrequest waitrequest Input 1
add_interface_port mem avm_mem_writedata writedata Output data_width
add_interface_port mem avm_mem_write write Output 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_address address Input 4
add_interface_port csr avs_csr_writedata writedata Input 32
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_readdata readdata Output 32
add_interface_port csr avs_csr_read read Input 1
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


proc elaborate_me {}  {
    set_port_property avm_mem_address WIDTH_EXPR [get_parameter_value ADDRESS_WIDTH]
    set_interface_property fftin dataBitsPerSymbol [get_parameter_value DATA_WIDTH]
}

proc validate_me {}  {
    if { [get_parameter_value USE_FIX_ADDRESS_WIDTH] == 1 }  {
        set_parameter_property FIX_ADDRESS_WIDTH ENABLED true
        set_parameter_value ADDRESS_WIDTH [get_parameter_value FIX_ADDRESS_WIDTH]
    } else {
        set_parameter_property FIX_ADDRESS_WIDTH ENABLED false
        set_parameter_value ADDRESS_WIDTH [get_parameter_value AUTO_ADDRESS_WIDTH]
    }
}